name: Build Windows EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Tools
      run: |
        pip install pyinstaller keyauth
    - name: Build EXE
      run: |
        pyinstaller --onefile app.py
    - name: Upload Result
      uses: actions/upload-artifact@v3
      with:
        name: GhostLadyLoader
        path: dist/app.exe
